- name: Evaluate Generator User
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', 'generator-user.yml') }}"

- name: Evaluate Transformer User
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', 'transformer-user.yml') }}"

- name: Evaluate USD Prices Topic
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', 'usd-prices-topic.yml') }}"

