apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: 3partitions-3replicas
  namespace: kafka-cluster
spec:
  config:
    retention.ms: 60000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3
